### ISSUE TITLE
hi not working

### ISSUE THREAD

**Issue by chonamdoo** [Coolerfall/Android-AppUninstallWatcher#5]
lollipop not working T_T

**Comment by coolerfall** [comment]
Can you give me some detail information?

**Comment by chonamdoo** [comment]
i have device samsung s6 edge, nexus 5x  
AppUninstallWatcher delete app not working

**Comment by coolerfall** [comment]
Use ps and grep in adb shell to check if watcher process existed.

**Comment by chonamdoo** [comment]
@Coolerfall  ok thx
